### ISSUE TITLE
程序跑不起来，是姿势不对吗

### ISSUE THREAD

**Issue by xiaxuesis** [opendatalab/magic-html#11]
按照说明，也安装成功了，但是每次指定一个网页提取的时候，都是报错，不知道是哪里的问题啊
![test](https://github.com/user-attachments/assets/2541bb47-2863-4b09-b47b-12c2bfb5ae4b)

**Comment by sixgad** [comment]
@xiaxuesis 从截图来看是成功提取到内容了 ，传入的html源码是什么样子的呢
