### ISSUE TITLE
怎样输出markdown格式的内容

### ISSUE THREAD

**Issue by lygiants** [opendatalab/magic-html#13]
![image](https://github.com/user-attachments/assets/108d852a-592d-480d-8d6b-af9861bd7b2a)
![image](https://github.com/user-attachments/assets/f9cb6627-da1f-482d-bc46-74ac17ea5a19)
执行程序后返回数据是正文部分的html源码, 怎样使其输出位markdown格式数据, 程序支持传入参数指定格式吗, 还是需要获取html数据后自行处理呢

**Comment by sixgad** [comment]
@lygiants 抽取程序返回数据是正文部分的html源码，可使用markdownify等开源库可将html转md

**Comment by lygiants** [comment]
好的好的, 谢谢~
