### ISSUE TITLE
自定义规则

### ISSUE THREAD

**Issue by szj2ys** [opendatalab/magic-html#5]
对于有些广告嵌入文中或末尾的去除不了，可以有方法去除吗。

比如这篇微信文中，https://mp.weixin.qq.com/s/-KCFD0h43J-YRDmFf71lSQ
提取的结果有多余的广告，要怎么去除

<img width="618" alt="image" src="https://github.com/user-attachments/assets/5e6db51f-22e2-4a67-bd54-79da1fdcb762">

**Comment by sixgad** [comment]
@szj2ys 公众号文章样式比较丰富，来源于多种排版编辑器，上述提供的例子中尾部内容存在于主体区域中，可以在后续数据清洗环节中尝试剔除
