### ISSUE TITLE
微信文章报错

### ISSUE THREAD

**Issue by naah69** [opendatalab/magic-html#6]
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/fa65cb69-2aa2-4b0d-bce0-d94d28cb89f1">

```python
from magic_html import GeneralExtractor
import requests

# 初始化提取器
extractor = GeneralExtractor()


url = 'https://mp.weixin.qq.com/s?__biz=MzI2MzEwNTY3OQ==&mid=2648988210&idx=1&sn=cb5dd15280d63143d0ce706a713026c2&chksm=f34fab2e3a5a3a6d92f8dd43afbdbc0c29737f973967b5f059f10f2a129da293fd3b4350f7ed&scene=27'
resp = requests.get(url)
html=resp.text

# 文章类型HTML提取数据
# data = extractor.extract(html, base_url='https://www.baidu.com')

# 论坛类型HTML提取数据
# data = extractor.extract(html, base_url=url, html_type="forum")
# 微信文章HTML提取数据
data = extractor.extract(html, base_url="https://mp.weixin.qq.com", html_type="weixin")

print(data)

```

**Comment by sixgad** [comment]
@naah69 requests.get(url) 直接请求公众号文章获取不到数据的，返回的是验证页面

**Comment by naah69** [comment]
我拿掘金的文章试了下也不行，没有内容
```python
from magic_html import GeneralExtractor
import requests

# 初始化提取器
extractor = GeneralExtractor()


url = 'https://juejin.cn/post/7304867278566899764?utm_source=gold_browser_extension'
resp = requests.get(url)
html=resp.text

# 文章类型HTML提取数据
data = extractor.extract(html, base_url='https://juejin.cn')

print(data)

```
{'xp_num': 'others', 'drop_list': False, 'html': '<html></html>', 'title': None, 'base_url': 'https://juejin.cn'}
```log

```

**Comment by naah69** [comment]
> @naah69 requests.get(url) 直接请求公众号文章获取不到数据的，返回的是验证页面

我debug了下，发现可以拿到内容
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/b73df368-9869-44ac-a504-789885a4be84">

![image](https://github.com/user-attachments/assets/3e00f68d-eead-4c18-9e82-c18ed1acb106)

**Comment by sixgad** [comment]
@naah69 如你所说“debug了下，发现可以获得网页请求响应内容“，那么抽取结果是否正呢？这边测试是没问题的
![image](https://github.com/user-attachments/assets/84e091c1-28ed-44ea-9067-ae1570fce68b)
![image](https://github.com/user-attachments/assets/b766be89-ed5e-442a-926b-a522c3606100)

**Comment by naah69** [comment]
> @naah69 如你所说“debug了下，发现可以获得网页请求响应内容“，那么抽取结果是否正呢？这边测试是没问题的 ![image](https://private-user-images.githubusercontent.com/20274790/353674328-84e091c1-28ed-44ea-9067-ae1570fce68b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTQ2NzcsIm5iZiI6MTcyMjM5NDM3NywicGF0aCI6Ii8yMDI3NDc5MC8zNTM2NzQzMjgtODRlMDkxYzEtMjhlZC00NGVhLTkwNjctYWUxNTcwZmNlNjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAyNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MGMzZWFlODFhOGFlMzBiZjY1ZGMwOTM2NTdmZTNhZTFkM2FjYzdjZTU4ZjE1ODY4N2E0MjUxY2ZkYjliOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WmH0EkksBJzRPn_PuNuYNOW6A13lJz0r2QZq-y9lQvA) ![image](https://private-user-images.githubusercontent.com/20274790/353674435-b766be89-ed5e-442a-926b-a522c3606100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTQ2NzcsIm5iZiI6MTcyMjM5NDM3NywicGF0aCI6Ii8yMDI3NDc5MC8zNTM2NzQ0MzUtYjc2NmJlODktZWQ1ZS00NDJhLTkyNmItYTUyMmMzNjA2MTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAyNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MDAzMWIzYjFhNzZjZDg1ZDBmMDkyOGRjZGRhMjE3ZmI3MGJlMWEzMTEyNjJkNjUxYjU5YTIzMWFmMWQ0M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4gt2v_JI1awzA0EU_F_BqACTZs-rId4TgIesoN5IdM)

我这边微信是报错的，其他平台都抽不出来

我这边的版本如下：
os： macos 12.5 arm
python: 3.8.18
magic_html：0.1.2

**Comment by naah69** [comment]
@sixgad 能麻烦问下那边的环境和安装方式吗
